### PR TITLE
Added defaultCalendar function

### PR DESCRIPTION
**Pull request by ddrury**
As per email conversation

### CODE REVIEW

**Comment by fisharebest** [comment]
Thanks.  After our discussion about the public `$d`, `$m` and `$y` member variables, I've been looking at shifting more of the functionality into the `ext-calendar` library.

(The advantage being that these external libraries are much easier to test in isolation, and hence have full unit-tests, etc.)

So, I've changed the API to return a calendar object instead of a calendar escape string, which should work better with these changes.  Instead of creating a GregorianDate, you would create a CalendarDate, and pass a GregorianCalendar object in the constructor...

**Comment by ddrury** [comment]
Well,

The chart now works with RTL languages and displays the scale with 
native characters, a problem was that the length of the year character 
string in Hebrew is longer than that of an Arabic language so I've had 
to change the scaling to suit. I don't suppose you happen to know which 
language would likely produce the longest strings would you?

Regards
David

Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by fisharebest** [comment]
Hebrew is likely to be the longest, as it uses a "roman numerals" style, with variable lengths.

All other languages have a simple substitution of digits 0-9

**Comment by ddrury** [comment]
Sorry about this - another question

I can't get my head around this locale/language/I18N inter-relationship.

If I want to display a number in the local language, how do I do it.

i.e. something like

$people = count($controller->people);
echo  I18N::number($people); // doesn't work!!


Regards
David

Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by fisharebest** [comment]
```php
$people = count($controller->people);
echo  I18N::number($people); // doesn't work!!
```

It should work.

```php
echo  I18N::number(1234); // should give "1,234" (in English locales)
```

If you want hebrew numerals, then these are only used for dates (not for general numbers), and hence are only accessibly by taking a JewishDate object containing that year, and formatting it with (from memory) `->format('y')`

**Comment by ddrury** [comment]
Oh well that makes it simple, it was a simple number (not a date) so I 
don't have to worry!

Regards
David

Please consider the environment before printing this e-mail



------ Original Message ------

**Pull request merged**
