### PR TITLE
Convert media files to the right code page on windows hosted sites, othe...

### PR DESCRIPTION
**Pull request by magicsunday**
...rwise files containing special chars (german umlauts for instance) won't be displayed.

### CODE REVIEW

**Comment by KosherJava** [comment]
It looks like Patchwork-UTF8 1.2 was released
https://github.com/nicolas-grekas/Patchwork-UTF8/blob/master/CHANGELOG.md

**Comment by fisharebest** [comment]
> It looks like Patchwork-UTF8 1.2 was released

...and webtrees updated to in on 2015-01-18 ;-)

**Comment by KosherJava** [comment]
Does that mean that the issue is automatically resolved? or is it now possible to fix it?

**Comment by fisharebest** [comment]
It means that as soon as I get time, I will read the documentation, and see if we can use it.

**Pull request closed without merging**
