### PR TITLE
Update British Monarchs and Prime Ministers History files and Create a New Zealand Prime Ministers History File

### PR DESCRIPTION
**Pull request by RAMINCNZ**
A small start to my contributions to WebTrees..

These files have been operational on my site so hopefully will be ok to add to main..

My apologies if I have created errors in the process, haven't quite got my head round modifying files and Commits and Pulls.. I do hope I have it right at this point

Updated The Above files added one and modified ModuleService.php to include line for New Zealand Prime Ministers

Rick Malkin

New Zealand - Nu Tirani

### CODE REVIEW

**Comment by arbor95** [comment]
What is the reason for not including this pull request?

**Comment by kiwi3685** [comment]
> What is the reason for not including this pull request?

I don't know Greg's reason (workload?), but I see a few possible issues:
- British Prime Minister list is out of date now. 
- Use of nicknames. Is that required? If yes, I think they should be in escaped double-quotes, not single. I wouldn't use them myself. Notes might be better?. 
- Use of Nu Tirani as New Zealand's alternative/ Maori name is very controversial. Very rarely, if ever, seen or used. Most people would use Aotearoa. It might be useful in a Māori language version, combined with a full Māori translation file.

**Comment by fisharebest** [comment]
> I don't know Greg's reason (workload?)

The Kings/Queens are fine - but I can't accept just part of a PR.

The new names are all inconsistent with existing ones - why `Mary Elizabeth Truss`, and not `Alexander Boris dePfeffel Johnston`?)

Maybe the full/legal names are OK for the NZ data?

> Use of Nu Tirani as New Zealand's alternative/ Maori name is very controversial. Very rarely, if ever, seen or used. Most people would use Aotearoa.

This is a question for the New Zealanders to answer.

**Comment by RAMINCNZ** [comment]
> > What is the reason for not including this pull request?
> 
> I don't know Greg's reason (workload?), but I see a few possible issues:
> 
>     * British Prime Minister list is out of date now.

When I first added these files everything was current. It would not be that hard to update (my fault for not doing so earlier) as each new Prime Minister came into 'power'. And the current British PM list is by far more out of date than this one. 

> 
>     * Use of nicknames. Is that required? If yes, I think they should be in escaped double-quotes, not single. I wouldn't use them myself. Notes might be better?.

Nicknames are not required, however for those that do have them, as I understand, their nicknames were used publicly (in the Media etc) quite often. Notes might be a better way of providing the info. I have started adding notes to the Monarchs file.. It is pretty much a link to the individuals page on Wikipedia. I could if desired do this with the PMs files too..


> 
>     * Use of Nu Tirani as New Zealand's alternative/ Maori name is very controversial. Very rarely, if ever, seen or used. Most people would use Aotearoa. It might be useful in a Māori language version, combined with a full Māori translation file.

It may be controversial. I can accept that. And for sure it can be removed. It is my personal choice to use Nu Tirani NOT Aotearoa..

I'm still new at this game and do not want to create 'issues' within the community..

Rick Malkin
New Zealand

**Comment by RAMINCNZ** [comment]
> > I don't know Greg's reason (workload?)
> 
> The Kings/Queens are fine - but I can't accept just part of a PR.
> 
> The new names are all inconsistent with existing ones - why `Mary Elizabeth Truss`, and not `Alexander Boris dePfeffel Johnston`?)
> 
> Maybe the full/legal names are OK for the NZ data?

I cannot quite recall how I got 'full names' for those that have them. IT could have been from the Wikipedia pages. These could be standardised for consistency.  I guess having full names might be consistent with how we our 'family data' could be deemed a standard. Worthy of debate..

> 
> > Use of Nu Tirani as New Zealand's alternative/ Maori name is very controversial. Very rarely, if ever, seen or used. Most people would use Aotearoa.
> 
> This is a question for the New Zealanders to answer.

As stated in last reply it can be removed..  It is my personal preference..

Rick Malkin
New Zealand - Nu Tirani

**Comment by Saintes-Martin** [comment]
From my perspective, consistency is the most important issue. If we use Harold Wilson for example, then we should also use Boris Johnson. Those are the names they were recognised by, and unless they are your family members, there’s no need for more.

So long as it’s easy for any user to add or remove data from a ‘history file’ or ‘timeline’ perhaps we should not worry too much? For example, I have a British social history events listing, and if I come across an event which may have been of interest to people in my tree, I like to add that.

**Comment by RAMINCNZ** [comment]
I have updated NewZealandPrimeMinisters.php removing 'Nu Tirani' and updating names to commonly used in New Zealand.

Updated BritishPrimeMinisters.php PM names to commonly used and added NoteLinks to some PMs. Can be further updated as required.

Updated BritishMonarchs.php adding two Note links. One to Elizabeth II and one to Charles III as examples. Can be updated as required.

Rick M
New Zealand

**Comment by arbor95** [comment]
seems as if you only have to change tab-char and blank char in BritishMonarchs.php starting in the line with
........ "1 EVEN Charles III\n2 TYPE
thx for the updates

**Pull request merged**
