### PR TITLE
Plcaes tab - use different colour for the individual's own events

### PR DESCRIPTION
**Pull request by arbor95**
change the color of the icon on map for birth and christening of the selected individuum to red.

### CODE REVIEW

**Comment by arbor95** [comment]
hi Greg
perhaps you can help resolving the unsuccessful checks.
thanks Franz

**Comment by fisharebest** [comment]
The code-check is complaining that you have `elseif` at the start of a line.  It should be on the previous line, after the `}`.

Would this be a simpler approach?  It makes it easy to modify all the icons for the individual.

```php
    protected const OWN_ICONS = [
        'INDI:BIRT' => ['color' => 'red', 'name' => 'baby-carriage fas'],
        'INDI:CHR'  => ['color' => 'red', 'name' => 'water fas'],
    ] + self::ICONS;

```


```php
                $icons = $fact->record() === $indi ? static::OWN_ICONS : static::ICONS;
```

```php
                        'icon'    => $icons[$fact->tag()] ?? static::DEFAULT_ICON,
```

**Comment by arbor95** [comment]
what to do to handle the remaining unsuccessful check?

**Comment by arbor95** [comment]
How to  handle:
Added line #L153 was not covered by tests
and the others "Added line"

**Comment by fisharebest** [comment]
> How to handle:
> Added line #L153 was not covered by tests
> and the others "Added line"

You can ignore this.

It says that there are no tests that use these lines of the code.

But none of this module has any tests yet.

**Comment by fisharebest** [comment]
Thanks!

**Pull request merged**
