### PR TITLE
V2 Update views/admin/location-edit.phtml - replace Geosearch

### PR DESCRIPTION
**Pull request by ddrury**
This should be installed after https://github.com/fisharebest/webtrees/pull/3088. as script in views/admin/location-edit would have changes introduced here over-written

- Replaced geosearch with leaflet-control-geocoder (Fixes issue https://github.com/fisharebest/webtrees/issues/2991)
- Added map reset button 
- Removed redundant code.

### CODE REVIEW

**Comment by fisharebest** [comment]
Something up with my styling?  Can you post a screendump showing what it *should* look like?

Screen Shot 2020-01-21 at 12 09 36

**Comment by ddrury** [comment]
I sometimes find I have to run `npm run production` twice to get everything in place. Compiling with sass seems to fix it.

Anyway here's a couple of screenshots
demo1
demo2

**Comment by fisharebest** [comment]
> I sometimes find I have to run npm run production twice

Aha.  That does it.

**Comment by ddrury** [comment]
Re npm run production. I _think_ the problem is sequencing in that the postCss line runs before mix.styles produces vendor.css therefore on first run the previous vendor.css is used. On 2nd run the recently produced vendor.css is compressed.

By using sass, all the css files are merged and minified in one action so it always works

**Comment by ddrury** [comment]
Thats it, I'm done now!

**Pull request merged**
