### PR TITLE
Set min zoom level for all map types

### PR DESCRIPTION
**Pull request by ddrury**
For all map instances, ensure default value for min zoom level is set even if module setting is missing. 

Despite this fix it is still possible to get more than one world displayed when the width to height ratio of the map div is very large (very wide browser windows).

I suppose we could calculate the minzoom based on that ratio but I'm not sure it's worth the effort. This suffices for most practical purposes

### CODE REVIEW

**Comment by fisharebest** [comment]
> even if module setting is missing

Settings should always be present?  It is set in one of the migration scripts https://github.com/fisharebest/webtrees/blob/master/app/Module/GoogleMaps/Schema/Migration5.php

Perhaps this is broken for some people/installations/upgrade paths?

+1 for replacing magic numbers with constants!

There's another magic number `6`, as in `MAX_ZOOM - 6`.

Perhaps get rid of it by having separate constants to represent the minimum/maximum/default value of both parameters?  e.g. something like

```
const GM_MIN_ZOOM_MINIMUM = 1;
const GM_MIN_ZOOM_DEFAULT = 2;
const GM_MIN_ZOOM_MAXIMUM = 14;

const GM_MAX_ZOOM_MINIMUM = 1;
const GM_MAX_ZOOM_DEFAULT = 15;
const GM_MAX_ZOOM_MAXIMUM = 20;
```

**Comment by ddrury** [comment]
> Settings should always be present

OK, I did it as a bit of defensive programming - would you prefer that the defaults be removed?
I'll extend the constants as suggested and as we have a max_zoom preference, maybe it should also be set on each map instance (probably not as important as min_zoom) what do you think?

**Comment by ddrury** [comment]
changes made as requested

**Comment by fisharebest** [comment]
We have a lot of code related to zoom levels, which leads to a complicated UI in places.
I find it tedious to choose a zoom-level for each of the places in the GM module.

I wonder if we can simplify/automate this?

Perhaps calculate the zoom by looking at all the other places with the same parent place.
Then use a bounding rectangle that includes all of them.

**Comment by ddrury** [comment]
Yeah, I agree, I think it should always be the case that on 
initialisation we set the min/max zoom levels and use the content to 
determine the actual zoom level (bounding box as you say)

I'd started to do this with the PR I recently withdrew. There is a huge 
amount of javascript "almost but not quite" duplication in the current 
code and it gets a bit impenetrable at times.

I'll have another rummage and see what falls out. I'd really like to get 
rid of the StreetView stuff - any chance?

BTW I've written an OpenStreetMap module using leaflet. Have a look at 
http://webtrees.drury.me.uk/individual.php?pid=I274&ged=drury.ged . The 
admin pages aren’t anywhere near complete yet!

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by fisharebest** [comment]
> I'd really like to get rid of the StreetView stuff - any chance?

Me too.  I'm off work for a week, so should have lots of time...

#1158

**Comment by Amgine0** [comment]
OpenStreetMap module envy! pleaseohpleaseohplease?

**Pull request merged**
