### PR TITLE
Fix #3784. Suppresses GEDCOM NOTE facts from Family Report for all fa…

### LINKED ISSUE #3784: 2.0.13 - Family Report prints raw shared note number even with disabled notes
In some families I have shared notes.

When I print a **Family Report** and disable the option **Show notes**, it still prints the raw shared note number (like @N20474@) even if the Show Notes option is disabled.

image

### PR DESCRIPTION
**Pull request by ekiczek**
…mily members if "Show notes" is unchecked.

With "Show notes" checked:
Screen Shot 2021-03-16 at 8 33 22 PM

With "Show notes" unchecked:
Screen Shot 2021-03-16 at 8 33 41 PM

### CODE REVIEW

**Comment by ekiczek** [comment]
P.S. - I was hoping there would be a more elegant way to do this. If you know of a better way, I'm happy to modify the PR, just let me know.

**Comment by fisharebest** [comment]
> I was hoping there would be a more elegant way to do this. If you know of a better way, I'm happy to modify the PR, just let me know.

I think that all we need to do is add `NOTE` to the definition for the variable `ignore`.

**Comment by ekiczek** [comment]
> I think that all we need to do is add `NOTE` to the definition for the variable `ignore`.
> 
> https://github.com/fisharebest/webtrees/blob/2.0.13/resources/xml/reports/family_group_report.xml#L39

Thanks for the tip! Should be all set now.

**Comment by fisharebest** [comment]
Thanks!

**Pull request merged**
