### PR TITLE
Lists as Modules

### PR DESCRIPTION
**Pull request by ric2016**
As suggested in Issue #2120.

Some implementation notes:

For now, I have kept and adapted existing classes and views (e.g. ListController, views), this could be cleaned up later.

Setting the access levels on the new list modules affects (as usual) other modules using the lists, see e.g. TopSurnamesModule (if IndividualListModule isn't accessible, top surnames are still displayed, but without links to the lists). For the list access level settings, I had to migrate the respective database table (Migration42.php).

Note that in this initial implementation, several UI elements still create lists directly, e.g. source-page.phtml via families-table.phtml. I'm not sure if these should be routed via the new modules as well.

### CODE REVIEW

**Comment by fisharebest** [comment]
> For the list access level settings

Some types of module have access levels - block, chart, menu, report, sidebar, tab
Others are simply enabled/disabled.

I wasn't expecting lists to have access levels.  My expectation was that this feature would simply allow users to

* disable unused lists (e.g. "shared notes")
* provide new types of list - perhaps lists of certain facts or events 
* provide replacement versions of existing lists

Since the contents of the list are already filtered for privacy, I'm not sure there is a need to set an access level for them.

I will be very busy next week, and so it may take me some time to review this.

> Note that in this initial implementation, several UI elements still create lists directly, e.g. source-page.phtml via families-table.phtml. I'm not sure if these should be routed via the new modules as well.

That's an interesting question.  More thought is needed.

**Comment by ric2016** [comment]
> I wasn't expecting lists to have access levels.

I guess it's debatable whether this feature is actually very useful. In any case, it doesn't affect most aspects of the implementation (e.g. even without access levels, TopSurnamesModule still has to check whether IndividualListModule is enabled, and so on). Since most other 'main' components have access levels, it probably doesn't hurt to keep them here as well for consistency.

> Since the contents of the list are already filtered for privacy, I'm not sure there is a need to set an access level for them.

Similar arguments could be made e.g. for charts - why do we allow access levels there?

(As long as they don't introduce too much additional complexity (both in develoment and in administration), I'm generally always in favor of additional configuration options.)

**Comment by magicsunday** [comment]
Please do not use closures all over the place.

**Comment by ric2016** [comment]
> Please do not use closures all over the place.

I used them in this case to preserve the existing function signatures and implementations as much as possible.

I have to ask though: Is this general webtrees development policy, and if so, is there some kind of guide for this? It's sometimes hard to do the right thing here ...

**Comment by magicsunday** [comment]
This is just my personal preference as closures passed to public methods make code more difficult to read and unterstand.

**Comment by fisharebest** [comment]
> Similar arguments could be made e.g. for charts - why do we allow access levels there?

Perhaps we should remove access levels from charts?

Perhaps the requirement for access levels should depend on the specific module, not on the type of module.  `ModuleHasAccessLevelInterface`?

I can see some modules that are only useful for certain users.  For example:

* the "Missing data report" is only useful to users with "Edit" role.
* the "Pending changes report" is only useful to users with "Moderate" role.

In both these cases, the "access level" does not allow us to select "Editors" or "Moderators" - the acces level is based on reading the data, not writing the data.

Perhaps 

> Please do not use closures all over the place.

I have not had time to look at the code in detail, but a couple of comments.

`$router` can return `null` - but we pass the return value to `e()` - which can only take a `string`.

It is not obvious why we use `$router` instead of calling `ModuleListInterface::listUrl()` directly?

But I have only had a *very* quick look at the code.  I hope to have more time at the weekend.

**Comment by ric2016** [comment]
Regarding the access levels: In my view, they are useful regardless of the character of the module and its data. If the site admin e.g. wants to hide specific charts, lists etc from visitors, for whatever reason (in order to entice them to sign up maybe?) - why shouldn't he be able to configure this?

**Comment by ric2016** [comment]
> `$router` can return `null` - but we pass the return value to `e()` - which can only take a `string`.

I missed a few null checks - I'll amend the pull request.

> It is not obvious why we use `$router` instead of calling `ModuleListInterface::listUrl()` directly?

I thought it would be cleaner this way (abstracting the url generation out of the views) - the views shouldn't contain any (complex) logic with regard to how to generate urls in my opinion, and this was intended as a step in that direction; while at the same time preserving the existing function signatures and implementations as much as possible. (It also makes the views more flexible, as they could be used outside a ModuleListInterface context)

**Comment by fisharebest** [comment]
> I thought it would be cleaner this way (abstracting the url generation out of the views)

I think you can still do this by passing the module instead of `$router`.

```
$module = $module_service->findByInterface('IndividualListModule::class)->first();
echo printTagCloud($tree, $module, ....);

...

function printTagCloud(Tree $tree, ?ModuleListInterface $module, ....) {
    if ($module instanceof ModuleListInterface) {
       echo '<a href="' . module->listUrl($tree, ['surname' => $surrname]) ."' . $surname . '</a>'
    } else {
       echo '<span>' . $surname . '</span>';
    }
}
```

**Comment by ric2016** [comment]
> I think you can still do this by passing the module instead of `$router`.

Sure, that also works. I still think this isn't optimally abstract, but it's not that important overall. I'll make this change everywhere `$router` is used now.

**Comment by ric2016** [comment]
I have updated the PR as suggested.

**Comment by fisharebest** [comment]
Thanks for this.  I have merged it in.

FYI, I decided to replace the `component enum (...)` with `interface varchar()` in the `wt_module_privacy` table.

It's a little simpler, and I think a little more flexible.

**Pull request closed without merging**
