### PR TITLE
GoogleMaps pedigree map chart bug fixes

### PR DESCRIPTION
**Pull request by ddrury**
- incorrect zoom level when only one place
- sidebar click on "view the individual" goes to wrong destination (bubbles up the DOM to parent click event)

Further - just noticed that ~ lines 1438 to 1499 implement a right click context menu - trouble is it uses googlemaps apiv2 calls which no longer exist. It seems to be a reasonably long winded process to write something new and as it only provides zooming & positioning facilities which can be easily replaced by dragging & (mouse zoom or zoom buttons) I wonder if it's worth it. My vote is to remove it

Later - I've removed it

### CODE REVIEW

**Comment by ddrury** [comment]
BTW I have a further PR that simplifies the pedigree map HTML by removing tables - it depends on this PR although it could be merged into this if you wish

**Comment by fisharebest** [comment]
> it could be merged into this if you wish

Please don't ;-)

I'm currently separating out the various parts of this PR...

**Comment by fisharebest** [comment]
I've merged some of the changes.  Can you rebase when you get a chance.  Ta.

PS - this could have been 3 or 4 separate PRs - each of which would have been much quicker to review.

**Comment by ddrury** [comment]
`I've merged some of the changes. Can you rebase when you get a chance. Ta.`
Done
`PS - this could have been 3 or 4 separate PRs`
Yeah - sorry, they became inter-connected

**Comment by fisharebest** [comment]
Can you fix the conflicts?  Ta!

**Comment by ddrury** [comment]
just done so (I hope!)

**Comment by fisharebest** [comment]
> just done so (I hope!)

Not quite?

If I run
```
git checkout -b ddrury-GoogleMapsChart master
git pull https://github.com/ddrury/webtrees.git GoogleMapsChart
```

and view the file `app/Module/GoogleMapsModule.php`,  I see this around line 1390

```
<<<<<<< HEAD
						$js .= 'var marker = createMarker(point, "' . Filter::escapeJs($name) . '","<div>' . $dataleft . $datamid . $dataright . '</div>", "';
						$js .= '<div class=\"iwstyle\">';
						$js .= '<a href=\"module.php?ged=' . $person->getTree()->getNameUrl() . '&amp;mod=googlemap&amp;mod_action=pedigree_map&amp;rootid=' . $person->getXref() . '&amp;PEDIGREE_GENERATIONS=' . $PEDIGREE_GENERATIONS;
						$js .= '\" title=\"' . I18N::translate('Pedigree map') . '\">' . $dataleft . '</a>' . $datamid . $dataright . '</div>", "' . $marker_number . '");';
=======
						$js .= "var marker = createMarker(point, \"" . Filter::escapeJs($name) . "\",\"" . $dataleft . "<div class='relation'>" . $datamid . $dataright . "</div>\", \"";
						$js .= "<div class='iwstyle'>";
						$js .= "<a href='module.php?ged=" . $person->getTree()->getNameUrl() . "&amp;mod=googlemap&amp;mod_action=pedigree_map&amp;rootid=" . $person->getXref() . "&amp;PEDIGREE_GENERATIONS={$PEDIGREE_GENERATIONS}";
						$js .= "' title='" . I18N::translate('Pedigree map') . "'>" . $dataleft . "</a>" . $datamid . $dataright . "</div>\", \"" . $marker_number . "\");";
>>>>>>> 7bb13808e93d8205953e539e1b64035defb65e17
```

It looks like quotation marks have been fixed in the master branch, and you have edited the same code in your branch...

**Comment by ddrury** [comment]
I think I fixed it but forgot to push!!

Hopefully now ...

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by ddrury** [comment]
Oh hell

**Comment by fisharebest** [comment]
> Oh hell

Relax.  There's just a block of 4 lines to manually edit.
I'm out for the rest of the evening, so no rush...

**Comment by fisharebest** [comment]
I'm guessing the "zoom problem" relates to the "redraw map" button.

IMHO, this button is not needed.  F5 does the same thing, and it just adds clutter to the map.

So, I've taken it out.  I don't think this breaks anything else.

Also, I don't think we can combine addresses and places.  I see things like this

> 1 The Gree, Ambridge, Borsetshire, England BO1 2FG, Ambridge, Borsetshire, England

I've merged the rest.

**Comment by ddrury** [comment]
hm didn't think the address thing through. Do you think the place +
coordinates is sufficient for the tooltip

Regards
David
On 14 Jun 2016 19:29, "Greg Roach" <notifications@github.com> wrote:

I'm guessing the "zoom problem" relates to the "redraw map" button.

IMHO, this button is not needed. F5 does the same thing, and it just adds
clutter to the map.

So, I've taken it out. I don't think this breaks anything else.

Also, I don't think we can combine addresses and places. I see things like
this

1 The Gree, Ambridge, Borsetshire, England BO1 2FG, Ambridge, Borsetshire,
England

I've merged the rest.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fisharebest/webtrees/pull/962#issuecomment-225973307>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAGYQ2_zFfWBI7d7Dn6O08C50US9ePhrks5qLvMcgaJpZM4IuboJ>
.

**Comment by ddrury** [comment]
I've found another bug with the pedigree map - sometimes for example a mother appears on two markers and the father on none - no idea why - I'll investigate

**Comment by ddrury** [comment]
It seems to be something to do with multiple markers on exactly the same location - I thought there was something in the code to offset them slightly - ongoing

**Comment by ddrury** [comment]
I don't think this is a bug as such - it seems to be down to the resolution of the mouse's calculated position. When a lot of markers are clustered on the same point the current algorithm changes the marker icon for each of the first 4 duplicates then starts shifting the position slightly for each extra duplicate.

As the icons are only identified by generation, it seems much more sensible to use the sidebar to select the right person.

Unless you disagree I don't intend to pursue this

**Comment by fisharebest** [comment]
> it seems to be down to the resolution of the mouse's calculated position

In that case, I'd probably leave it.

**Pull request merged**
