### PR TITLE
Suppress a few elements when printing

### PR DESCRIPTION
**Pull request by ddrury**

### CODE REVIEW

**Comment by fisharebest** [comment]
Ref the CSS changes.

In some cases, there is a 4th icon - such as shared notes.

Instead of adding the 3 elements copy/edit/delete, would it work to add the parent element? `<div class="editfacts">`?

**Comment by ddrury** [comment]
I can't find the 4th icon you're talking about, but anyway, unfortunately not every occurrence of those icons are wrapped in `<div class="editfacts">`
For example the edit & delete icons a few levels down the hierarchy in `<div id="header_accordion1">`

**Comment by fisharebest** [comment]
screen shot 2016-05-08 at 21 40 47

**Comment by ddrury** [comment]
OK, changed as suggested

**Pull request merged**
