### PR TITLE
Update TopSurnamesModule.php

### PR DESCRIPTION
**Pull request by tunandras**
I hope it’s technically alright.

### CODE REVIEW

**Comment by tunandras** [comment]
The modified module fixes two issues.

**Comment by tunandras** [comment]
The modified module fixes two issues.

**Comment by fisharebest** [comment]
> The modified module fixes two issues.

What are the two issues?

**Comment by tunandras** [comment]
1. After setting “Number of items to show” input field in “Configure — Top
surnames” form, the user may not understand the result if the “Minimum
number of occurrences” input field on Control Panel’s Preferences page
specifies not the expected.

2. If user sets too high number in “Minimum number of occurrences” field a
short message “No data available in table” appears by
webtrees\packages\datatables-1.10.7\js\jquery.dataTables.min.js JavaScript
file without the possibility of translating (and only if presentation style
is table; all other styles result no message at all)

(I wrote them in comments into the code...)



---
A hálóhelyem: tuna.hu, az Index egyik rovata pedig a Dívány
<http://divany.hu/>.

**Comment by fisharebest** [comment]
I think the problem is that:

a) we have configuration options (`COMMON_NAMES_REMOVE`, etc.) that should only apply to the common surnames list (in the Family tree statistics block).
b) we are using these in the Top surnames block

IMHO, a better solution is to ignore these options in this block. https://github.com/fisharebest/webtrees/commit/784e1b4bc2b28a54307c23676a35e0393f5f7e80

**Comment by fisharebest** [comment]
8e7b29b fixes the untranslated text in empty lists

**Pull request closed without merging**
