### PR TITLE
Fixes issue 2240, failing to render custom module templates

### PR DESCRIPTION
**Pull request by magicsunday**
Fixes issue 2240, failing to render custom module templates #2241

### CODE REVIEW

**Comment by fisharebest** [comment]
I have some ideas for this in a local branch, which use namespaces.

Modules would have namespace for their own views.  e.g. `mymodule::path/to/view`
The core code would use a "global namespace".  e.g. `::path/to/view`.

This would prevent conflicts - if two modules both created a view with the same name, then one would see the view of the other.

This gets registered with something like `$module->registerViewPath()`

Modules would be able to replace views in the core code (and in other modules!) by specifying replacements.  e.g.

```
public function replaceViews() {
    return [
        '::some/core/module' => 'mymodule::replacement/for/the/view';
    ];
}
```

Using functions instead of simple search paths also allows module to choose views at run-time.

For example, they could supply different views for different themes or admin/user/visitor.

The namespace idea comes from https://laravel.com/docs/5.7/packages#views

**Comment by magicsunday** [comment]
Sounds good. Please add. 😄

**Comment by fisharebest** [comment]
The issue I had not yet resolved was the access levels.

The access level is part of the core code - not part of the module.

So, a module does not know if it can/will be used - and therefore does not know if it should replace existing views.

I left this work "on hold" so I could think about the way that modules interact with access levels...

**Comment by fisharebest** [comment]
This functionality should now be provided by https://github.com/fisharebest/webtrees/commit/3e4bf26f9f16d92152484c56e3629888fb6019d5

**Comment by magicsunday** [comment]
If I register a namespace in a module, shouldn't this be enough, that every subsequent call to view() uses this module specific namespace first, so I'm not require to always include the namespace?

    $this->viewResponse(
        $this->name() . '::template-name',
        ....
    );

**Pull request closed without merging**
