### PR TITLE
Change method access modifiers for easier extensibility of module

### PR DESCRIPTION
**Pull request by ric2016**
Note: In my opinion there is little reason to have private methods in any of the module classes, so perhaps change this everywhere?

### CODE REVIEW

**Comment by fisharebest** [comment]
These functions are internal implementation details for the module.

IMHO, they should not be exposed, and they should not be relied on.

If my IDE tells me that a function isn't used, I may decide to remove/refactor it - which will break your code.

If the logic in these private functions is sufficiently useful that it will be used elsewhere, then perhaps it needs moving to its own `Service` (i.e. business logic) class?

**Comment by ric2016** [comment]
So what if I want to slightly modify an existing module? Currently I have to re-implement all private methods, and align them with each change in the original module. How is that any better?

Having protected methods doesn't mean you're not allowed to change them - That happens all the time anyway.

**Comment by ric2016** [comment]
Thank you - I appreciate it.

**Comment by fisharebest** [comment]
> If the logic in these private functions is sufficiently useful that it will be used elsewhere, then perhaps it needs moving to its own Service (i.e. business logic) class?

I have just implemented this.

All these functions are now public methods in a new `IndividualFactsService`.

**Pull request merged**
