### PR TITLE
Translation Census French

### PR DESCRIPTION
**Pull request by mikejpr**
I hope it's all correct!

### CODE REVIEW

**Comment by ddrury** [comment]
Hi Mikejpr

I have a couple of comments (but bear in mind that Greg is the final arbiter of all things webtrees)

1. CensusColumnCondition[language]php generally return a short summary of the Marital status - could you shorten the text slightly in CensusColumnConditionFrench.php?
2. Consider writing tests to cover your code changes - see tests/app/census/* for examples

**Comment by fisharebest** [comment]
Hi Mike - thanks for this.

In addition to the questions from @ddrury:

I have made a change to CensusColumnConditionXxxxx.  An additional translation is required.

**Comment by mikejpr** [comment]
Hi Dave,

Thanks for your comments.

To 1: How many characters can we use? I uploaded the finished file in my webtree and tested the result there. The table looked good because the characters were not shortened or fields are long enough, so that I had not seen the sense of using an abbreviation.
To 2: Unfortunately, I do not quite understand what you mean? What should I do in the directory? Put the file I have corrected? Remember that I am not a programmer, so please be more clear so that I can help.
To 3: I did found a specific date. The census begins at the 3 Thursday in the year, so I suppose it did not occur at all in one day. I have based the fields/informations from the information of [Wikipedia](https://fr.wikipedia.org/wiki/Histoire_du_recensement_de_la_population_en_France#Renseignements_personnels_recueillis_de_1831_.C3.A0_1975).

**Comment by fisharebest** [comment]
> How many characters can we use?

This tool is to help people create accurate transcripts of the original census.

In UK censuses, the status is written as Mar or Unm
In US censuses, the status is written as M or S

I have never seen a French census, so I do not know how the status is wrttten there.

> Unfortunately, I do not quite understand what you mean?  Remember that I am not a programmer.

Some of the webtrees code has automated tests.  These allow us to work on the code, and be confident that we have not broken any existing functions.  If you do not understand how this works, then no problem.   Someone else can write the tests.

> The census begins at the 3 Thursday in the year

Do you mean the 3rd Thursday in January?

**Comment by mikejpr** [comment]
> This tool is to help people create accurate transcripts of the original census.
> In UK censuses, the status is written as Mar or Unm
> In US censuses, the status is written as M or S
> I have never seen a French census, so I do not know how the status is wrttten there.

This should be very complicated if you want to create exactly the same structure as in the French census.

from 1831 to 1876
sexe masculin // male
- garçons // boys
- hommes mariés // married men
- veufs // widowers

sexe feminin // female
- filles // girls
- femmes mariées // married women
- veuves // widows

[Example](http://mnesys-portail.archives-finistere.fr/?id=viewer&doc=accounts%2Fmnesys_cg29%2Fdatas%2Fir%2Fserie_m%2FFRAD029_00000006M.xml&page_ref=19414&lot_num=1&img_num=1&index_in_visu=)

since 1881
Position dans le ménage // household status
- chef // head  (but it can be a male or a female depending of the household if the men is dead or not)
- sa femme // his wife
- enfant // child
- domestique // domestic

but many other possibility can exists depending who live in the household in relation to the head. Here some possibilities:
- mère // mother
- beau-frère // brother-in-law
- belle-mère // stepmother
- sœur // sister
- nièce // niece 

...

[Example](http://mnesys-portail.archives-finistere.fr/?id=viewer&doc=accounts%2Fmnesys_cg29%2Fdatas%2Fir%2Fserie_m%2FFRAD029_00000006M.xml&page_ref=19649&lot_num=3&img_num=1&index_in_visu=)


> Do you mean the 3rd Thursday in January?

Exactly as you write.

**Comment by fisharebest** [comment]
> This should be very complicated if you want to create exactly the same structure as in the French census.

If possible, we want exactly the same structure.

> garçons // boys

So, in this column, we write "garçons" (or garçon")?

Do you have an example of an original census.  It might be easier if we can see it.

**Comment by mikejpr** [comment]
I already add 2 links into my last comment. In the first one you can see the structure for the first block. 
But of course they are little modifications in the years. I send you an email with some screenshot of the header structure. So that it be more clear.

Normally you are right that one boy will be garçon and not garçons, but because it's the summary of a column they take the plural. For each line we have a number "1", and at the end the summary for that page. In the screenshot that I will send you (1872-1876.jpg) you can see how it is shown.
With a free interpretation of the data I would also prefer use the singular.

**Comment by fisharebest** [comment]
@mikejpr - I have updated the code with the information in your emails.  Thanks!

**Pull request merged**
