### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by ddrury**
Pedigree map: Add link to each persons own pedigree map (lost in recent commit)
Individual Tab: Correct HTML errors (lines 1922 - 1931) addresses issue #1015

### CODE REVIEW

**Comment by ddrury** [comment]
Oops - just got your email!

**Comment by fisharebest** [comment]
I'd actually removed the links to the pedigree map on purpose...

On the side-bar, clicking these elements highlight the corresponding individual on the map.
In the map, I thought it was confusing for them to do something different.

**Comment by ddrury** [comment]
Oh OK,

In which case do you want to remove it from the popup as well (Lines 
1307 & part 1308)? and the global $PEDIGREE_GENERATIONS from function 
pedigreeMapJavascript();

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by fisharebest** [comment]
> In which case do you want to remove it from the popup as well 

I think so, yes.

**Comment by ddrury** [comment]
Are you doing this and the mismatched `<div>`'s or shall I close this and resubmit it with those fixes

**Comment by fisharebest** [comment]
> Are you doing this and the mismatched <div>'s

I was going to cherry-pick those changes from your PR - but if it is easier for you to resubmit them, then do that...

**Comment by ddrury** [comment]
Ok give me a few minutes

**Pull request closed without merging**
