### PR TITLE
Update IndividualRepository.php

### PR DESCRIPTION
**Pull request by magicsunday**
Fixed LIKE part in SQL queries.

### CODE REVIEW

**Comment by fisharebest** [comment]
Do you need the raw SQL statement?
It looks like the code is just missing the trailing `%`.

**Comment by magicsunday** [comment]
I tried without raw but this didn't changed anything. The raw its needed.

See "Total dead" on https://dev.webtrees.net/demo-dev/index.php?route=module&module=statistics_chart&action=Chart&ged=demo

**Comment by fisharebest** [comment]
The code is looking for `\` followed by `n` - not a newline.

Just change the quotes.

```
@@ -1382,7 +1382,7 @@ class IndividualRepository implements IndividualRepositoryInterface
             ->where('i_file', '=', $this->tree->id());
 
         foreach (Gedcom::DEATH_EVENTS as $death_event) {
-            $query->where('i_gedcom', 'NOT LIKE', '%\n1 ' . $death_event);
+            $query->where('i_gedcom', 'NOT LIKE', "%\n1 " . $death_event . '%');
         }
 
         return $query->count();
@@ -1399,7 +1399,7 @@ class IndividualRepository implements IndividualRepositoryInterface
             ->where('i_file', '=', $this->tree->id())
             ->where(function (Builder $query): void {
                 foreach (Gedcom::DEATH_EVENTS as $death_event) {
-                    $query->orWhere('i_gedcom', 'NOT LIKE', '%\n1 ' . $death_event);
+                    $query->orWhere('i_gedcom', 'LIKE', "%\n1 " . $death_event . '%');
                 }
             })
             ->count();
```

I've just put this change on the server, and it seems to work now:
https://dev.webtrees.net/demo-dev/index.php?route=module&module=statistics_chart&action=Chart&ged=demo

**Comment by magicsunday** [comment]
The result is still the same. Please take a look at the chart below "Total dead". This prints 100% for living and dead.

**Comment by magicsunday** [comment]
You are right, I changed the quotes and removes the DB::raw and it seems to work. Maybe the demo-server is outdated again?

**Comment by fisharebest** [comment]
> Maybe the demo-server is outdated again?

The code is reset and updated every few hours.
The data is reset every day.

**Pull request merged**
