### PR TITLE
Added PHP7 return types to methods according doc block

### PR DESCRIPTION
**Pull request by magicsunday**

### CODE REVIEW

**Comment by fisharebest** [comment]
> according doc block 

I hope the docblock is correct ;-)

**Comment by fisharebest** [comment]
Oops.  Lots of things broken.  Application won't start.

**Comment by magicsunday** [comment]
Uh :(

**Comment by magicsunday** [comment]
The getPreference method is fixed in this commit: https://github.com/fisharebest/webtrees/pull/1863/commits/0cee83a35d1ab5e6973971301a2dcb95b8560c33

**Comment by fisharebest** [comment]
The preferences are stored in the database as strings.
They are retrieved as strings.
So, I think it is clearer if we always save them as strings.

**Pull request merged**
