### PR TITLE
Charts as Modules: Remove hard-coded references

### PR DESCRIPTION
**Pull request by ric2016**
As suggested in a comment in Pull Request #884 (which was already completed at that time), this removes hard-coded links to the relationships chart (currently, these links are displayed but redirect to the main page if the relationship chart is inaccessible).

These links are now provided via a separate method in `ModuleChartInterface`, returning null if not applicable for the respective chart. Thus, custom chart modules may also provide these links. If no suitable chart is active/accessible, the link itself is no longer displayed.

### CODE REVIEW

**Comment by fisharebest** [comment]
I do not think that `Module::getLinkForRelationship` belongs in `class Module`.

Elsewhere, we use code like this:

```
if (Module::getModuleByName('XXX')) {
    ...
    // Code that uses module XXX
    ...
}
```

The relationship chart module can take 1 or 2 individuals.
Other charts have a variable number of individuals (lifespans, timelines).

Perhaps add a function `ModuleChartInterface::getChartLink(array $individual) { }` which generates the link.

Then we could have something like (in class `Functions`??)

```
function xxx(Individual $individual1, Individual $individual2) {
    if (Module::getModuleByName('RelationshipsChartModule')) {
        $link = RelationshipsChartModule::getChartLink(array($individual1, $individual2));
        return $relationship_link...
    } else {
        return $relationship_name...
    }
}
```

I think this is a cleaner structure,
What do you think?

**Comment by ric2016** [comment]
The idea was to remove any 'hard-coded' references to a specific chart (not only hard-coded uris).
I.e. something like `if (Module::getModuleByName('RelationshipsChartModule'))` is still problematic.
(One reason for this is that users may want to use a different relationship chart, which would e.g. be a solution for issue #913 )

> I do not think that Module::getLinkForRelationship belongs in class Module.

ok - we could just move this method to Functions?

**Comment by ric2016** [comment]
Do you have any further thoughts on this?

Basically, the question is whether to only use links to a specific chart (RelationshipsChartModule in this case), or to allow links to a chart of a specific type (any chart displaying relationships), which are then resolved to a suitable specific chart. Or do you think this isn't necessary at all?

**Comment by fisharebest** [comment]
I think that the best way to implement this sort of problem is to use PHP interfaces to allow a module to state its capabilities.

For example, this sort of logic,

``` php
// relationships.php
$relationship_algorithms = [];
foreach ($modules as $module) {
  if ($module instanceof InterfaceCalculatesRelationships) {
    $relationship_algorithms[] = $module;
  }
}

if (count($relationship_algorithms) > 1) {
  // Show an option to allow the user to choose algorithm.
}
```

Or perhaps

``` php
foreach ($modules as $module) {
  if ($module->hasCapability('canCalculateRelationships') {
    $relationship_algorithms[] = $module;
  }
}
```

Or perhaps a "hook" system like drupal or wordpress.


Whatever, this approach means that we move away from modules that are just a simple chart/menu/report/etc.   Instead, a module is just a set of capabilities.

IMHO, the best fix for #913 would be to add this functionality to the core code.

**Comment by ric2016** [comment]
> IMHO, the best fix for #913 would be to add this functionality to the core code.

Ok, I'll have to adjust the code a bit though - It turns out the approach as described there is not correct in all cases.

**Comment by fisharebest** [comment]
I think the latest 2.0 code solves this.

**Comment by ric2016** [comment]
> I think the latest 2.0 code solves this.

I don't see how - The links are still generated regardless of whether a relationship chart is actually enabled (in FunctionsPrintFacts line 542).
Note also that there seems to be a missing route definition here (the generated link referes to the undefined route 'relationships').

**Comment by ric2016** [comment]
ok, that will work. 

If no chart isn't accessible to the current user (Access level set via module adminstration), a link is still shown though. In general the chart is still actually accessible, it just doesn't appear in the chart menu. Is it supposed to work this way? Probably the same for reports etc., when a url is entered directly.

**Comment by fisharebest** [comment]
You are right.  I was looking for the module in the list of *all modules*, not the list of *available charts*.
This was skipping the check for access level.

Fixed.

> Is it supposed to work this way? Probably the same for reports etc., when a url is entered directly.

This is similar to typing URLs of private individuals.
A similar check is needed.

Fixed.

**Pull request closed without merging**
