### PR TITLE
fixed gender pronouns from exclusively male

### PR DESCRIPTION
**Pull request by dmangot**
All the pronouns were male, but users of webtrees are not exclusively maIe.   I tried to give my daughter and account to edit our family tree and it said 'his', even though she is not male.  This pull request aims to fix those conditions.   Thanks!

### CODE REVIEW

**Comment by fisharebest** [comment]
I agree with the sentiment of this change, but will implement it slightly differently.  At present, it will cause all 60 current translations to become untranslated, and require that all translators re-translate it.

Since the change does not affect the meaning, and since most languages have already translated this using their own gender-neutral pronoun, I'll also need to update all the existing translation files.

Incidently, I've had complaints the other way, from linguists who tell me that "their" is plural, and should not be used as a singular...  There may also be differences between british and american usage. See https://en.wikipedia.org/wiki/Singular_they

**Comment by fisharebest** [comment]
When this

> Add this individual, his direct line ancestors, and their families.

is changed to this

> Add this individual, their direct line ancestors, and their families.

we are using "their" as both singular and plural in the same sentence.  It becomes unclear whether the second "their" is the same as the first "their"

These sentences probably need rewriting completely.

**Comment by dmangot** [comment]
Thanks Greg.   If there are translations files that need to be edited or rewriting of some sentences that needs to be done, I'm happy to put in some time for that and offload you.   Just let me know specifically how I can help and I'll modify the PR.

Cheers.

**Comment by vytux-com** [comment]
Also for future reference you should not modify the vendor files as they are 3rd party and changes would be overridden by any future updates.

**Comment by fisharebest** [comment]
For the clippings cart, we actually know the individual, so we can accurately use "his" or "her".

For the help text, it needs rewriting completely.

**Pull request closed without merging**
