### PR TITLE
Further pedigree chart work

### PR DESCRIPTION
**Pull request by ddrury**
Moved all positioning logic into the controller. Now the only elements that are absolutely positioned are the node containers. Simplified the line drawing logic in javascript by using sosa triples (ie child + parents)  and using the node location as the base for calculating the point positions.

This has no impact on Meliza's requirements

### CODE REVIEW

**Comment by fisharebest** [comment]
1) Instead of creating new global functions `get_menu()` and `gotoPreviousGen()`, would these be better as functions within the controller?

2) Do we need to create the global JS variable `WT_PEDIGREE_CHART`.  Can we use just `(function() {...})();`

**Comment by ddrury** [comment]
Re you queries below

1. I wanted too but thought as they generated output they shouldn't go 
in the controller (I'll get the hang of this MVC stuff one day).

2. I think this was one of my changes but not recently - The original 
intention was to have it as an instantiated object with parameters 
passed into it, but it never worked out like that.

I'll make the changes and push then up.


Regards
David

Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by fisharebest** [comment]
@ddrury - The "pedigre map" chart (in the google maps module) uses the PedigreeController->ancestors array - which no longer exists.

Can you take a look?

**Comment by ddrury** [comment]
Oops, Ok

Regards
David

Please consider the environment before printing this e-mail



------ Original Message ------

**Pull request merged**
