### PR TITLE
Added totalIndisWithSourcesPercentage

### PR DESCRIPTION
**Pull request by TheDutchJewel**
Update Statistics.php, IndividualRepository.php and IndividualRepositoryInterface.php with totalIndisWithSourcesPercentage

### CODE REVIEW

**Comment by TheDutchJewel** [comment]
This pull request has been waiting months or approval/merging.

Do I need to change anything?

**Comment by TheDutchJewel** [comment]
This pull request is at almost a year old. Is there anything against accepting it?

**Comment by fisharebest** [comment]
> This pull request is at almost a year old. Is there anything against accepting it?

Do we have/need an equivalent for families?
Do we have/need an equivalent for "without sources"?

**Comment by TheDutchJewel** [comment]
> > This pull request is at almost a year old. Is there anything against accepting it?
> 
> Do we have/need an equivalent for families? Do we have/need an equivalent for "without sources"?

Might be handy.

I added a new pull request with the changes.

**Comment by TheDutchJewel** [comment]
New pull request: https://github.com/fisharebest/webtrees/pull/4678

**Pull request closed without merging**
