### PR TITLE
Don't display on the date of death next to birth

### PR DESCRIPTION
**Pull request by wooc**

### CODE REVIEW

**Comment by wooc** [comment]
https://www.webtrees.net/index.php/en/forum/help-for-ver-1-7-3/30953-on-the-date-of-death

**Comment by fisharebest** [comment]
1) I cannot reproduce the problem using BIRT and DEAT.  I can only reproduce it using `EVEN`

```
1 EVEN
2 TYPE BIRT
2 DATE 1892
1 DEAT
2 DATE 1892
```

Can you show me the GEDCOM data for this record?

**Comment by wooc** [comment]
Disable SHOW_PARENTS_AGE parameter.

The GEDCOM is:
1 BIRT
2 DATE 1892
1 DEAT
2 DATE 1892

**Comment by fisharebest** [comment]
> Disable SHOW_PARENTS_AGE parameter.

Of course!

**Pull request merged**
