### PR TITLE
Fixes #1622

### LINKED ISSUE #1622: ErrorController::noRouteFound
After login as admin the ErrorController::noRouteFound is triggered and redirects (line 57) me to "admin_trees_manage.php" without any error message.

### PR DESCRIPTION
**Pull request by magicsunday**
@fisharebest Please take a look at the following changes. This fixes for me the admin login to a private tree.

If no tree is available at all and the user is no admin he gets the mentioned message "This user account does not have access to any tree" displayed. If admin he get redirected to "admin_trees_manage.php".

### CODE REVIEW

**Comment by fisharebest** [comment]
The change to `session.php` fixes the problem for me.

I have merged these changes.

The changes to `index.php` (`// Force login`) seem to duplicate the logic in `ErrorController::noRouteFound()`.  Am I missing something?

**Comment by fisharebest** [comment]
OK - I see what I am missing. Redirect to admin page, not home page.

**Comment by fisharebest** [comment]
> Redirect to admin page, not home page.

I am sure I saw this happen.  But I cannot reproduce it.

**Comment by magicsunday** [comment]
The problem is:

    Session::get('GEDCOM', $first_tree_name);

won't return the first_tree_name, as the session array contains an empty "GEDCOM" entry. Session::get checks only if the value isset. I don't know if this could safely changed to "empty" or if something else will break.

After changing: 

    $from_session = Session::get('GEDCOM', $first_tree_name);
	
to:

    $from_session = Session::get('GEDCOM');
    $previous_tree_name = !empty($from_session) ? $from_session : $first_tree_name;

it seems fine.

**Comment by fisharebest** [comment]
> as the session array contains an empty "GEDCOM" entry

Aha!

In `session.php`, we only write non-empty values to `$_SESSION`.
In `index.php`, we always write it - even if it is empty.

So, the actual bug is that we write an empty value.

**Comment by magicsunday** [comment]
You are right. 

    if ($tree_name) {
        Session::put('GEDCOM', $tree_name);
    }

seems to work too.

**Comment by fisharebest** [comment]
Merged.  Thanks.

**Pull request merged**
