### PR TITLE
DRAFT: New and updated historical core-modules

### PR DESCRIPTION
**Pull request by Lars1963**
**WIP**

**NEW**
- module `HistoryChancellorsGerman`
- module `HistoryPresidentsFrench`
- module `HistoryMonarchsFrench`

**DELETED**
- module `FrenchHistory` in favor of new enhanced french modules

**added:**
-   * missing entries
-   * localized wikipedia sources

**fixed:**
-   * typos in dates
-   * typos in informatioan

**enhanced:**
-   more facts in most modules
-   use datetype JULIAN in dates prior to 15th october 1582
-   rename the modules for consistent naming and better overview in folder

**WIP as follow up to this pr:**
- [ ] new module `HistoryFactsFrench`
- [x] new module `HistoryPresidentsGerman`
- [ ] new module `HistoryMilitaryFactsWorld`
- [ ] new module `HistoryPandemicsWorld`
- [ ] new Module `HistoryMonarchsBelgium`

### CODE REVIEW

**Comment by Lars1963** [comment]
ci is not happy :)

**Comment by Lars1963** [comment]
@fisharebest please review

As soon this pr is okay by you and merged, I'll do a follow up pr.

BTW: congrat to britisch victory ;-)

**Comment by hartenthaler** [comment]
Thank you very much for your contribution to optimize the historic modules. Two remarks: 
- it is a good idea to mark dates as Julian but in my opinion, it makes no sense to mark a year like 1451 as Julian because a year without day and month is less precise than the difference between julian and gregorian.

**Comment by Lars1963** [comment]
@hartenthaler 
> * it is a good idea to mark dates as Julian but in my opinion, it makes no sense to mark a year like 1451 as Julian because a year without day and month is less precise than the difference between julian and gregorian.

You might be right there, but honestly: is it harmfull? Or should one prefer systematic use? 
@fisharebest Greg, what do you think?

> * At least the title of a module and the field TYPE should be translatable (see my historic modules for that)

We had that diskussion before. None of the core-modules are translatable for now, so that is not my primary goal here. 

I'd like to complete my other planned basic historic modules first. And then, in a next step, (for the 2.1.x-Release?) see how we can make all of the basic core-modules translatable.

**Comment by fisharebest** [comment]
> @fisharebest Greg, what do you think?

You have made lots of changes in this PR.  It is difficult to extract parts of it.  I can only merge/reject the entire PR.

1) You have renamed existing modules.  It is possible that a someone is relying on the existing names.  e.g.

```
class MyHistoricFacts extends BritishPrimeMinisters {
    public function historicEventsAll(): Collection
    {
        // Exclude modern ones
        return parent::historicEventsAll()->filter(.... date < 2000 ....)
    {
}
```

I am not sure there are benefits to this change.

2) You have split the French file into two.  Did this requirement come from a French user?

In the British files, monarchs and prime-ministers cover the same time period.  So, users might want just one or the other.  In the French files, monarchs and presidents do not overlap.  So it is far less likely that users will want just one or the other.  French users will need to re-enable these modules after the upgrade.

3) Julian years are formatted differently to Gregorian years.  They have an "era suffix" `CE` or `BCE`.  A Julian year will likely be surrounded by other Julian dates, so I think it would look better to see them with the same formatting.  So, yes, use `JULIAN` for julian years.

> At least the title of a module and the field TYPE should be translatable

IIRC, there is an open issue for this.

**Comment by Lars1963** [comment]
@fisharebest 
> 1. You have renamed existing modules.  It is possible that a someone is relying on the existing names

Okay, i didn't realize that. So yes, this would be a breakung change (I gues there are quit a lot of breaking changes in 2.1?).
IMHO, the benefit lies in consistent naming conventions combined with a better overview in the module folder.

So my question, would you support this one time breakting change or is it for you a reason to reject the PR?

> 2. You have split the French file into two.  Did this requirement come from a French user?
I actually came from some french and french speaking relatives of mine. The rest of `french history` will go into the new enhanced module `HistoryFactsFrench`. 

But, I do now realize, that I could combine Monarchs and Präsidents into one  (like the czech one). So I will revert these to and make them one file.


> 3.  .... So, yes, use `JULIAN` for julian years.

Thanks, I'll do continue to use it like that.




> 4. IIRC, there is an open issue for this.

Haven't found it, but anyhow that was my plan plan allready. I'll need some help from you, on how to accomplish that the best way. I know how @hartenthaler does it, but that is only for 2 languages. I would like to use your translationstool.

**Comment by Lars1963** [comment]
> @fisharebest
> 
> > 1. You have renamed existing modules.  It is possible that a someone is relying on the existing names
> 
> Okay, I didn't realize that. So yes, this would be a breaking change (I gues there are quit a lot of breaking changes in 2.1?).
> IMHO, the benefit lies in consistent naming conventions combined with a better overview in the module folder.
> 
> So my question, would you support this one time breakting change or is it for you a reason to reject the PR?
> 
> > 1. You have split the French file into two.  Did this requirement come from a French user?
> >    I actually came from some french and french speaking relatives of mine. The rest of `french history` will go into the new enhanced module `HistoryFactsFrench`.
> 
> But, I do now realize, that I could combine Monarchs and Präsidents into one (like the czech one). So I will revert these to and make them one file.
> 
> > 1. .... So, yes, use `JULIAN` for julian years.
> 
> Thanks, I'll do continue to use it like that.
> 
> > 1. IIRC, there is an open issue for this.
> 
> Haven't found it, but anyhow that was my plan allready. I'll need some help from you, on how to accomplish that the best way. I know how @hartenthaler does it, but that is only for 2 languages. I would like to use your translationstool.

**Comment by hartenthaler** [comment]
I agree that it is a good idea to have only one timeline in one historic data file. So I will separate German Presidents and Chancellors in my file. Or even better I will delete my module if the information is integrated into the core. But you should separate the Chancellors of GDR and BRD (western Germany) and Deutsches Reich, too. If I'm not interested in GDR history I would not like to appear their chancellors in my history. Make it as modular as possible. One timeline for one area of interest. Area of interest can be geographic or political or topics like pandemics or wars.

Maybe a special menu in the control panel would help the admin to manage more and more historic data files. But there is a deeper question behind: who decides about which historic data is of interest for the users. At the moment the admin selects the historic data files he thinks are of interest for his tree, but maybe a user from China knows Chinese history very well and likes to see Chinese history events even if all events in the tree are located in Europe because he likes to compare what happened in China at the time the events in the tree happened. Maybe the users should be able to select the history files, but the normal user will not find and use this possibility, so we should not make it too flexible.

Yes, the translation should be possible for `title`, `description`, and `TYPE` at least. I have done the translation for German only and left it open to others to do it for other languages.

I will use the marker for `julian` even for years now, too (in my file "wars and battle worldwide"). So we will be consistent.

We agree already in using markdown for formatting links. But the links should work even if an admin has switched off markdown for his trees. So there should be a space before the closing ")" like in `[wikipedia de](https://de.wikipedia.org/wiki/Konrad_Adenauer )`. And we have to be consistent in putting the links in SOUR or NOTE. I do not have a preference.

There was one user who tried to add PLAC to the historic data records. Interesting, because many events are related not only to a date but to a location, too. But this is not foreseen by the location management of webtrees and I found no consistent way how to use this because every webtrees installation has its own location management. So we should not use PLAC in historic data files.

**Comment by Lars1963** [comment]
> I agree that it is a good idea to have only one timeline in one historic data file. So I will separate German Presidents and Chancellors in my file. Or even better I will delete my module if the information is integrated into the core. But you should separate the Chancellors of GDR and BRD (western Germany) and Deutsches Reich, too. If I'm not interested in GDR history I would not like to appear their chancellors in my history. Make it as modular as possible. One timeline for one area of interest. Area of interest can be geographic or political or topics like pandemics or wars.

Mmm, that might be a good point of discussion. I first also wanted to seperate them, but as "Ahnenforschung" is not only "finding relatives", but in particular also finding lives-context for the person (where did he/she live, how did he/she live, how were the times, social circumstances, etc.), there is more than one aspect to look at.

Undoubtly, the post-war area of Germany is defined by the GDR and the BRD. Many families had relatives on both sides of the "iron curtain", so I would think GDR and BRD belong together in a historical context.

Maybe a special menu in the control panel would help the admin to manage more and more historic data files. But there is a deeper question behind: who decides about which historic data is of interest for the users. At the moment the admin selects the historic data files he thinks are of interest for his tree, but maybe a user from China knows Chinese history very well and likes to see Chinese history events even if all events in the tree are located in Europe because he likes to compare what happened in China at the time the events in the tree happened. Maybe the users should be able to select the history files, but the normal user will not find and use this possibility, so we should not make it too flexible.

I opened a Issue for this #3927 

> We agree already in using markdown for formatting links. But the links should work even if an admin has switched off markdown for his trees. So there should be a space before the closing ")" like in `[wikipedia de](https://de.wikipedia.org/wiki/Konrad_Adenauer )`. And we have to be consistent in putting the links in SOUR or NOTE. I do not have a preference.

I'll test this one: in Markdown there should not be a space, but if necessary I'll change that. I prefer `SOUR` for links, I think that is the best GEDCOM-way. I'm using `NOTE` for additional remarks to `EVEN`.


> There was one user who tried to add PLAC to the historic data records. Interesting, because many events are related not only to a date but to a location, too. But this is not foreseen by the location management of webtrees and I found no consistent way how to use this because every webtrees installation has its own location management. So we should not use PLAC in historic data files.

I've opened a issue for this #3928 
If not possible, I'll remove the `PLAC`-entries from the other files

**Comment by Lars1963** [comment]
I changed this PR into DRAFT-status. I will splitt it up, to make reviewing and discussion easier.

**Comment by Lars1963** [comment]
Closed in favor of multiple PR's for better discussion.

**Comment by Lars1963** [comment]
@hartenthaler please review PR #3930

**Pull request closed without merging**
