### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by ddrury**
Remove redundant link from sidebar HTML and fix mismatched DIVs

For some reason clicking on the gallery image on the pedigree map sidebar has stopped working. I've commented out the e.stopPropagation line for now which allows it to work but also triggers the info window popup

### CODE REVIEW

**Comment by fisharebest** [comment]
Thanks Dave!

**Comment by ddrury** [comment]
What about the mismatched divs?

**Comment by fisharebest** [comment]
> What about the mismatched divs?

Confused?  This PR looks like it fixed them...

**Comment by ddrury** [comment]
Doh,

Helps when you pull the changes doesn't it!

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by ddrury** [comment]
Have I got time to get one more PR to you - minor restructure of the 
pedigree map sidebar HTML to make click events easier

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by fisharebest** [comment]
> Have I got time to get one more PR to you

The 1.7.6 boat sailed an hour ago...

**Comment by ddrury** [comment]
Well in that case I'll go to town!!!

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Pull request merged**
