### PR TITLE
Adding 2 factor authentication 2FA to webtrees

### PR DESCRIPTION
**Pull request by kbwhizz**
Working for me locally on 2.1.20. Adds an extra box for Google authenticator code to be added by user. User enables it via the edit account page which provides a QR code to scan. Needs some tweaking and database fields adding to schema in setup wizard - user.secret and user_setting key/value pair of statusmfa and value 1 or <blank>. I hope it helps.

### CODE REVIEW

**Comment by arbor95** [comment]
Do you think a change of 2,983 files will be necessary to implement your change?

**Comment by kbwhizz** [comment]
Um. No. Sorry. Not very good with GitHub. Do I need to resubmit?

**Comment by arbor95** [comment]
best is: use the current code as starting point for your changes.

**Comment by fisharebest** [comment]
> Um. No. Sorry. Not very good with GitHub. Do I need to resubmit?

This documentation might help: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

I guess you made your changes against an older version of the code.
You need to "rebase" (re-apply) your changes against the latest version.

Or, if this is too difficult, it might be better to start again using the latest version of the `main` branch.

**Pull request closed without merging**
