### PR TITLE
Fixes #2307

### LINKED ISSUE #2307: 2.0 - Languages do not show up in Control Pannel / Languages
image

Recompiling languages makes no difference  composer webtrees:mo

### PR DESCRIPTION
**Pull request by magicsunday**
Fixes #2307

### CODE REVIEW

**Comment by xmlf** [comment]
Thank you!
It works very well.

**Comment by fisharebest** [comment]
I just pushed a slightly different fix for this.

**Comment by fisharebest** [comment]
Thanks for finding the problem.

**Comment by magicsunday** [comment]
glob sort the files, this is already done afterwards.

**Comment by fisharebest** [comment]
`glob()` sorts by filename - `it`, `fr`, ...

We need to sort by the local language name - "Italiano", "franćais", ...

**Comment by magicsunday** [comment]
Yes but Sorting of glob could be omitted.

**Comment by fisharebest** [comment]
> Yes but Sorting of glob could be omitted.

Of course!

It is not needed on any of the calls to `glob()` so I have updated all of them.

**Pull request closed without merging**
