### PR TITLE
Update messages.po

### PR DESCRIPTION
**Pull request by TranThieutn**
Add translation for Vietnamese

### CODE REVIEW

**Comment by fisharebest** [comment]
Hi @TranThieutn - thanks for the translation.

All updated `.PO` files should be merged by uploading them to https://translate.webtrees.net/projects/webtrees/webtrees-22/vi/#upload

This is for two reasons

1) it prevents merge conflicts
2) it merges the new translations to all branches of the code.

If you need help using the translation server, just ask.  Or you can send me the `.PO` file and I can upload it for you.

**Comment by shawnsavour** [comment]
Good to me, I'm from Vietnam also. Please approve this.

**Comment by fisharebest** [comment]
@TranThieutn - if you cannot use https://translate.webtrees.net, can you email the file to me so that I can upload it.

**Comment by iet-admin** [comment]
Hi @TranThieutn 

I want to include these changes, but you need to provide the full .PO file.

You can upload it to the translation server or email it to me.

**Comment by TranThieutn** [comment]
Hello, I edit directly here, so I don't have the file on my computer, you can download it directly in the installation file.

**Comment by fisharebest** [comment]
I have downloaded the file from github and uploaded it to the translation server.

**Pull request closed without merging**
