### PR TITLE
Update File.php

### PR DESCRIPTION
**Pull request by magicsunday**
Check result of mkdir and throw an exception im directory creation fails.

### CODE REVIEW

**Comment by fisharebest** [comment]
I can't check this right now, but I think that if `mkdir()` fails, then it will raise an `E_WARNING`.

We set `error_reporting()` to `E_ALL`, so this will already raise an exception?

**Comment by magicsunday** [comment]
This fix was adopted from https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#mkdir-race-condition

**Comment by magicsunday** [comment]
I thinks its better to check the result of the function. Before the functions returned true even if mkdir failed.

**Comment by fisharebest** [comment]
The `File` class is being removed.  Most of it has gone.

It will be replaced with `Flysystem`.

This will give two advantages.

1) testability - we will be able to use a mock-class to test file operations.
2) we can use either the "local" adpater or the "SFTP" adapter, to remove the need to `chmod 777 /data/`
3) we can store our data files anywhere - not just on our webserver.

**Pull request closed without merging**
