### PR TITLE
Report additions

### PR DESCRIPTION
**Pull request by sevtor**
The app/Report tool creates reports from the collected gedcom data. The current version has some limitation and shortcomings that this update addresses. A detailed description is included as a pdf file, and in short the changes are:

Report tries to place text on an exact position on a page. But many pitfalls on the way. Counting lines in a textbox is not enough, the lines may be set in different font sizes; converting lines to points in HTML uses a much too high number, which results in a lot of white space, especially for long reports (many pages). The PDF reports have problems to predict when the tool TcPdf will break a line or add a page. This applies to the files HtmlRenderer.php, ReportHtmlTextbox.php, ReportHtmlText.php, PdfRenderer.php, ReportPdfTextBox.php and ReportPdfText.php, 

The file ReportParserGenerate.php is responsible for the interpretation of the xml code that defines the layout and contents of the report. A number of addition have been introduced. 
(1) GetPersonName has got a new attribute, select=..., that allows the report to present the last name used or a combination of latest and surname at birth. Another attribute, fam_relation="1", will add the relation the current person to the start person of a report, e.g. mmf which means mother's mother's father. 
(2) The value that is returned by GedcomValue can be a very long string. An attribute truncate=... already exists but has been two new possibilities for dates: "Y" will give only the year and "d" gives the date with the three character short for the month, "dd mmm yyyy". 
(3) The calculation of the family relation that can be give with the name requires a substantial amount of code. 
(4) The xml keyword Facts returns all facts and events of the current object (person, family) in the order they appear. But in a report one wants chronological order and that has been implemented. A special addition is that a temporary gedcom event is introduced in the process, _SP_DEAT, which when a spouse has died, if applicable. This is used only during calculations, not added to the Gedcom database or file. This (hidden) gedcom value must be added to the gedcom.php file. (A similar presentation is given on the main page for each person.) 
(5) The keyword SetVar has been expanded with new possibilities for the attribute value=.... The value can now specify "@$xxx" which means the the value of xxx is interpreted as the name of the varible to select. Other new values are "@format" that responds PDF or HTML depending on whichever form of report is selected. "@$dump" can give some help in debugging new or modified reports. 
(6) Sometimes ancestors have married a relative. In pedigree charts these persons were given as separate persons, although with tha same name, birthdate, et c. But now such persons are detected and the second occurrance is given as "same person as ...". 
(7) Some errors are corrected.

### CODE REVIEW

**Comment by sevtor** [comment]
Unfortunately I used my own indentation rules and did not know how to fix it. So please make the corrections! 
And please tell me how I can use the tool StyleCI in the future.

**Comment by sevtor** [comment]
The static analysis checks that still fail have relate to code that "always" has been there. 

Therefore I want this pull request to be set to **'Ready for review'** !

**Comment by sevtor** [comment]
**PR ready for review!**

**Comment by sevtor** [comment]
This PR solved the 'Missing data' Feature Request. 
It also handles translations for custom modules, especially reports, where the title and description strings were un-translated (because the translations were included too late).

**Comment by BertKoor** [comment]
Is this PR still a candidate to be merged with the dev branch?
Headers & footers on reports are mentioned again in the forum:
https://www.webtrees.net/index.php/forum/2-open-discussion/39136-reports-download

**Comment by sevtor** [comment]
Yes it is!

**Comment by elysch** [comment]
Hello. 
I decided to try these changes. Generated a patch file and applied to a clean 2.1.20 sources directory. 

I got these errors:

```
can't find file to patch at input line 5939          
Perhaps you used the wrong -p or --strip option?     
The text leading up to this was:                     
--------------------------                           
|diff --git a/phpstan-baseline.php b/phpstan-baseline.php                                                 |index 8e433dded66..4596026fff8 100644               
|--- a/phpstan-baseline.php                          
|+++ b/phpstan-baseline.php                          -
-------------------------                           
File to patch:                                       
Skip this patch? [y]                                 
Skipping patch.                                      
1 out of 1 hunk ignored                              
can't find file to patch at input line 5952          
Perhaps you used the wrong -p or --strip option?     
The text leading up to this was:                     
--------------------------
|diff --git a/phpstan-baseline.php b/phpstan-baseline.php                                                 |index 4596026fff8..03a51d7ca51 100644               
|--- a/phpstan-baseline.php                          
|+++ b/phpstan-baseline.php                          
--------------------------                           
File to patch:                                       
Skip this patch? [y]                                 
Skipping patch.                                      
4 out of 4 hunks ignored                                                                                  

...                                                                                              

patching file app/Module/ModuleCustomTrait.php       Hunk #3 FAILED at 112.                               
1 out of 4 hunks FAILED -- saving rejects to file app/Module/ModuleCustomTrait.php.rej

...                                                                                                       

patching file app/Report/ReportParserGenerate.php    Reversed (or previously applied) patch detected!  Assume -R? [n]                                          
Apply anyway? [n]                                    
Skipping patch.                                      
3 out of 3 hunks ignored -- saving rejects to file app/Report/ReportParserGenerate.php.rej
```

Just in case it helps.

**Comment by elysch** [comment]
I dought this is right:

```
diff --git a/app/Gedcom.php b/app/Gedcom.php
index 1af380bbb33..b9881765ba0 100644
--- a/app/Gedcom.php
+++ b/app/Gedcom.php
```

```
@@ -595,8 +594,8 @@ private function gedcom551Tags(): array
             'INDI:BARM:DATE'             => new DateValue(I18N::translate('Date of bar mitzvah')),
             'INDI:BARM:PLAC'             => new PlaceName(I18N::translate('Place of bar mitzvah')),
             'INDI:BASM'                  => new BasMitzvah(I18N::translate('Bat mitzvah')),
-            'INDI:BASM:DATE'             => new DateValue(I18N::translate('Date of bat mitzvah')),
-            'INDI:BASM:PLAC'             => new PlaceName(I18N::translate('Place of bat mitzvah')),
+            'INDI:BASM:DATE'             => new BasMitzvah(I18N::translate('Date of bat mitzvah')),
+            'INDI:BASM:PLAC'             => new DateValue(I18N::translate('Place of bat mitzvah')),
             'INDI:BIRT'                  => new Birth(I18N::translate('Birth')),
             'INDI:BIRT:DATE'             => new DateValue(I18N::translate('Date of birth')),
             'INDI:BIRT:FAMC'             => new XrefFamily(I18N::translate('Birth parents')),
```

**Comment by elysch** [comment]
Is the line with a fixed "55.5" is right?

```
diff --git a/app/Report/PdfRenderer.php b/app/Report/PdfRenderer.php
index bbe261242b4..ba12d1416ea 100644
--- a/app/Report/PdfRenderer.php
+++ b/app/Report/PdfRenderer.php
```
```
@@ -363,8 +364,8 @@ public function setup(): void
             'UTF-8',
             self::DISK_CACHE
         );
-
-        $this->tcpdf->setMargins($this->left_margin, $this->top_margin, $this->right_margin);
+        $this->tcpdf->setPrintFooter(true);
+        $this->tcpdf->setMargins($this->left_margin, 55.5 /*$this->top_margin*/, $this->right_margin); // header-height?
         $this->tcpdf->setHeaderMargin($this->header_margin);
         $this->tcpdf->setFooterMargin($this->footer_margin);
         $this->tcpdf->setAutoPageBreak(true, $this->bottom_margin);
```

**Comment by sevtor** [comment]
Hello Elysch, I am sorry that I missed your comments earlier. I was traveling and and have been busy with other things since then, but now I have resumed this work. 

1. The file phpstan-baseline.php is use only when the PR tries check the code and as a user you do not need it.

**Comment by sevtor** [comment]
Hello Elysch! I am really sorry that I missed your comments earlier, but I have been very busy lately. 

1. The file phpstan-baseline.php is only used by the Pull Request and as a user  you should not have it. 
The file ModuleCustomTrait.php should not be patched, I don't understand how it came into your diff. 
You should check that the two rejected parts for ReportParserGenerate.php are actually already there (except for my comment about 2.1.x). 
2. The Gedcom.php file should not be patched at all. 
3. In PdfRenderer.php I have an explicit constant 55.5 because I could not find the value for the height of the header, as I tried to indicate in the comment. 

Recently I applied the changes I was using in wt 2.1.18 to a fresh installation of 2.1.20 and everything worked out fine and I am now using the patched 2.1.20. You can fetch these files from my repo sevtor/modules. 

I am now trying to figure out how I shall continue. The history of this PR is too long and files are modified and reverted so either I shall continue here or restart with a new PR. There are also some numerical constants in other places that I don't like but I hesitated earlier to make more elaborated changes to the code but now I know more about how to use php.

**Comment by sevtor** [comment]
I am now working intensively with updates and will create a new PR that will replace this one!

**Comment by elysch** [comment]
Hello sevtor.

I've noticed errors in character encoding and I'm beginning to think it has to do with this code. I documented those errors at [https://github.com/fisharebest/webtrees/issues/5129](https://github.com/fisharebest/webtrees/issues/5129)

Have you noticed or corrected something that could help?

Thanks

**Comment by elysch** [comment]
This message is to document that sevtor found the problem. It's related to the character #xA0 that is part of the Hebrew letter named "nun" (maybe others too), and was being replaced as if it was only a non-breakable space.

The fix is described in [https://github.com/fisharebest/webtrees/issues/5129](https://github.com/fisharebest/webtrees/issues/5129)

**Pull request closed without merging**
