### PR TITLE
Pedigree map - Fix page scroll on click of sidebar element

### PR DESCRIPTION
**Pull request by ddrury**
(2nd submission - code tidy)

See [Forum message](https://www.webtrees.net/index.php/en/forum/9-request-for-new-feature/37850-pedigree-map-scrolling-home). Prevent page scroll to top when clicking on the sidebar Relationship field.

(I thought we fixed this some time ago)

### CODE REVIEW

**Comment by fisharebest** [comment]
Replacing the link target `<a href=#>` with a click on the background prevents keyboard accessiblity.

A simpler option is `e.preventDefault()` in the event handler.

**Comment by arbor95** [comment]
The fix seems not to work together with the rural theme (wt 2.1.17)
Perhaps you can help jon48. See https://github.com/jon48/webtrees-theme-rural/issues/62

**Comment by ddrury** [comment]
I refer you to now closed pull request 
https://github.com/fisharebest/webtrees/pull/4798. As far as I can see 
jon hasn't incorporated this code.

Regards
David


------ Original Message ------
From "Franz Frese" ***@***.***>
To "fisharebest/webtrees" ***@***.***>
Cc "David Drury" ***@***.***>; "Author" 
***@***.***>
Date 15/07/2023 22:20:36
Subject Re: [fisharebest/webtrees] Pedigree map - Fix page scroll on 
click of sidebar element (PR #4774)

**Comment by arbor95** [comment]
Thx for the hint

**Pull request closed without merging**
