### PR TITLE
Allow sendmail command to be configured

### PR DESCRIPTION
**Pull request by dnrce**
Swift Mailer's default of `/usr/sbin/sendmail -bs` isn't always sufficient.

### CODE REVIEW

**Comment by fisharebest** [comment]
Do you think we should add validation to this parameter?

Allowing any value to be passed to `proc_*()` makes me nervous.

> Swift Mailer's default of /usr/sbin/sendmail -bs isn't always sufficient.

What changes do you need?  Different path?  Different executable name?  Different parameters?

**Comment by dnrce** [comment]
In my own case I need `/usr/bin/sendmail -oi -t`.

Good point on security. Would it be a better approach to only make this configurable via `config.ini.php`?

**Comment by fisharebest** [comment]
> Would it be a better approach to only make this configurable via config.ini.php?

Yes, I think so.  (See <https://12factor.net/config>)

**Comment by fisharebest** [comment]
I have updated the documentation at https://webtrees.net/faq/email/

Can you test the latest code for me?  Thanks.

**Comment by dnrce** [comment]
I would have updated but thanks for throwing the fix together so quickly! I have tested by applying this patch to my 2.0.3 installation and it works great.

**Comment by dnrce** [comment]
:+1: on the updated documentation as well. Thanks!

**Pull request closed without merging**
