### PR TITLE
Create DutchMonarchs.php, DutchPrimeMinisters.php and LowCountriesRulers.php

### PR DESCRIPTION
**Pull request by Lars1963**
Historical Fact Modules showing the dutch monarchs, a list of the prime-ministers with the names of their cabinets and a list of the rulers of the Low Countries

Signed-off-by: Lars van Ravenzwaaij <ict@ravenzwaaij.eu>

### CODE REVIEW

**Comment by Lars1963** [comment]
@fisharebest please review

**Comment by hartenthaler** [comment]
Willem-Alexander = Koningin ??? 

I would prefer if even the TYPE field is translatable, as I have done it in my historic data modules. See [german-wars-battles-worldwide](https://github.com/hartenthaler/german-wars-battles-worldwide)

**Comment by Lars1963** [comment]
> Willem-Alexander = Koningin ???
> 
> I would prefer if even the TYPE field is translatable, as I have done it in my historic data modules. See [german-wars-battles-worldwide](https://github.com/hartenthaler/german-wars-battles-worldwide)

Uuups. Copy-Paste-Error ;)

I see what you have done, but my intent was a simple core-module like e.g. https://github.com/fisharebest/webtrees/blob/main/app/Module/BritishMonarchs.php

@fisharebest Is it possible to change a custom module like the one from @hartenthaler into a tranlateble core-module? If yes, can you point out howto?

**Comment by Lars1963** [comment]
> For line 62 to 70:
> _NOTE Koningkrijk der Nederlanden_ should read _NOTE Koninkrijk der Nederlanden_ (there is no g in koninkrijk).

THX! I believe I'm living to long in Germany now. I seems I'm forgetting my mothers tongue.

**Comment by fisharebest** [comment]
Merged.  Thanks!

**Pull request closed without merging**
