### PR TITLE
Udate lang espanish

### PR DESCRIPTION
**Pull request by yako1984**

### CODE REVIEW

**Comment by fisharebest** [comment]
It is better to update translations using the project translation server.

https://translate.webtrees.net/projects/webtrees/

**Comment by yako1984** [comment]
Ok

**Comment by fisharebest** [comment]
FYI, the translation server cannot send emails at the moment - so you cannot register.  If you want an account, email me and I will set it up for you.

**Comment by yako1984** [comment]
bouzonmail@gmail.com

**Pull request merged**
