### PR TITLE
Add missing England 1921 Census

### PR DESCRIPTION
**Pull request by kiwi3685**
1921 Census file added, and CensusOfEngland changed to include it.

I noticed this census was missing for latest webtrees. Hope it's useful.

### CODE REVIEW

**Comment by ddrury** [comment]
There is an open issue for this - https://github.com/fisharebest/webtrees/issues/4374. I started producing a PR but the column(s) for "Number and ages of all living children ..." defeated me (seee attached image). It seems to me that this should be a number of columns not one as your PR proposes and I'm interested in how you'd visualise completing this column.
166883710-b1cf9077-6037-41b1-8685-e4cf49a49733

**Comment by kiwi3685** [comment]
Adding 17 columns to make it exactly as per the original document is ridiculously impractical.

The single column in my pull request is for free-form text that allows uswrs to add the same informatuion in a simple way that suits their own preferences. The aim shoulld be to capture the content and intent of the original document, not slavishly follow every part of the form. Some typical entries for that column from my own data include:

'Total 3 - 1 3y; 2 4y"
'2<1y'

**Comment by martins250** [comment]
Just hoping this can be included in the next webtrees version.

**Comment by fisharebest** [comment]
> Just hoping this can be included in the next webtrees version.

Not until we can decide how to implement these columns.

In other censuses, we have tried to copy the exact structure of the original document.

But such a large number of columns may be impractical.

I guess I need to implement both and see how they work in practice.

**Comment by kiwi3685** [comment]
Is it possible for a custom module to over-ride an existing census template, or even multiple ones?

**Comment by ddrury** [comment]
> But such a large number of columns may be impractical.

The United states 1941 census has 31 columns which is more than the England 1921 census is likely to have even including the child ages columns and that doesn't seen to cause problems.

**Comment by RAMINCNZ** [comment]
Hi There

Can we go ahead with this pull request any time soon?? And @kiwi3685  Maybe reopen this so we can get it done.

Keep Smiling

Rick M

**Pull request closed without merging**
