### PR TITLE
#4667 Fix Sqlsrv Setup

### PR DESCRIPTION
**Pull request by FrankWarius**

### CODE REVIEW

**Comment by fisharebest** [comment]
Hi Frank,

Can you run some tests for me.

1) You set `IDENTITY_INSERT OFF` after each insert.

We didn't do this in the previous code (But that code did not work...!).

Can you check that this statement is required.  e.g. will it work without it.

2) In SQL-Server, I think that you use `[` and `]` to quote table names.  This can be important if the prefix contains special characters.

Can you tell me if it still works when you replace
`'SET IDENTITY_INSERT ' . $prefix . 'user ON'`
with
`'SET IDENTITY_INSERT [' . $prefix . 'user] ON'`

**Comment by FrankWarius** [comment]
Hi Greg

> 1. You set IDENTITY_INSERT OFF after each insert.

I followed https://stackoverflow.com/questions/56560556/insert-data-in-laravel-identity-insert-is-set-to-off.
it seems You have to switch it On and OFF for every table.
Your actual fixes work for all migration scripts

> 2. In SQL-Server, I think that you use [ and ] to quote table names. This can be important if the prefix contains special characters.

Done and pushed.

Migration finished with creation of Config.ini.php but has an major issue with session table see #4669

**Comment by fisharebest** [comment]
Can you tell me if it is necessary to use `->unprepared()`.
Will it also work wtih `->statement()`?

**Comment by fisharebest** [comment]
Your PR adds some entries to `.gitignore`

It is recommended that this type of file are added to your global .gitignore file - not the project file.

I merged the `SET IDENTITY_INSERT` changes in 736b8b72ed0af202b700901a7965eb77c180581f

**Comment by FrankWarius** [comment]
> Can you tell me if it is necessary to use `->unprepared()`. Will it also work wtih `->statement()`?

I doesn't test statement(). I found https://stackoverflow.com/questions/56560556/insert-data-in-laravel-identity-insert-is-set-to-off. and there You found

> You can use DB::unprepared() instead of DB::statement().
> The difference is that statement() executes a prepared statement, while unprepared() uses PDO::exec() instead.
>
> Every prepared statement starts a new session (inside the same database connection) and because the SET IDENTITY_INSERT query is session-specific, it doesn't affect other prepared statements like the INSERT query.

**Pull request closed without merging**
