### PR TITLE
Added England & Wales1939 Register as Census

### PR DESCRIPTION
**Pull request by ddrury**
Have taken column headings from record rather than transcript and checked against the National Archives at http://www.nationalarchives.gov.uk/help-with-your-research/research-guides/1939-register/#4-what-information-can-i-find-in-the-1939-register

### CODE REVIEW

**Comment by fisharebest** [comment]
Thanks for adding the test cases!

Isn't `CensusColumnFullNameReversed` the same as `CensusColumnSurnameGivenNames` - or have I missed something?

**Comment by ddrury** [comment]
Nope, I missed that completely  - Am I close enough to warrant making 
the necessary changes?

Regards
David
Please consider the environment before printing this e-mail



------ Original Message ------

**Comment by fisharebest** [comment]
> Am I close enough to warrant making the necessary changes?

That's the only thing I spotted when reviewing the code, so if you can update this, I'll merge the PR.

**Comment by ddrury** [comment]
Hold fire - There's  case changes needed on a couple of file names

**Comment by fisharebest** [comment]
> Hold fire

While you are doing whatever this is, can I make one more (picky!) change.  Last one, I promise.

For consistency/clarity, can you rename `CensusColumnBirthDaySlashYear` to `CensusColumnBirthDayMonthSlashYear`, to match the existing `CensusColumnBirthDaySlashMonthYear`

**Comment by ddrury** [comment]
Can you clarify something for me. I'd named a file RegisterofEngland1939.php but called the class RegisterOfEngland1939 (lower case o in Of). I thought that composer didn't like things like that but travis-ci didn't pick anything up. For consistency I corrected the file name but did I really need to?

**Comment by fisharebest** [comment]
> Can you clarify something for me. I'd named a file RegisterofEngland1939.php but called the class RegisterOfEngland1939 (lower case o in Of)

These need to agree exactly.  It may work on case insensitive filesystems (e.g. FAT, NTFS), but won't work on case  sensitive ones (e.g. ext2/3/4)

> I thought that composer didn't like things like

It depends on which autoloader you are using.

For a classmap autoloader (where it scan every file, and creates an array of `class` => `file`) it doesn't matter.  For a dynamic autoloader (where each class is expected to be in a particular location), it does.

**Comment by ddrury** [comment]
> For a dynamic autoloader (where each class is expected to be in a particular location), it does

Shouldn't Scrutinizer pick up this type of error?

**Comment by fisharebest** [comment]
> Shouldn't Scrutinizer pick up this type of error?

Possibly.  But it does a static code analysis, and doesn't know whether you've installed the dependencies using `composer dump-autoload`  or `composer dump-autoload --optimize`.

**Pull request merged**
