### PR TITLE
allow use of GedcomRecordFactory for specific types, cleaned up.

### PR DESCRIPTION
**Pull request by ric2016**
again, see #3073 (also #3085).

Use of internal cache in GedcomRecordFactories (taken from GedcomRecord) should probably be refactored to use main cache.

### CODE REVIEW

**Comment by fisharebest** [comment]
FYI, I am not 100% happy with the factory code in the develop branch.

Specifically, it prevents many other classes (e.g. app/Services/*) from using dependency injection.

**Comment by ric2016** [comment]
Why are they prevented from using it? Do you mean remaining calls e.g. to Individual::getInstance, as in IndividualListService?

**Comment by fisharebest** [comment]
> Why are they prevented from using it?

Because these objects can be created *before* the modules are booted - which means that they will use the default factory objects - and not the ones created by your module.

**Comment by fisharebest** [comment]
For example, the DescendancyModule uses the SearchService - which needs IndividualFactory and FamilyFactory.

**Comment by ric2016** [comment]
I see - Possible solutions:

* Boot the (custom) modules earlier - This may not be possible/desirable for other reasons?

* Do not inject dependencies in the Constructor, but only when they are actually used the first time. This is how it's currently done in SearchService - Is that a problem? I guess it's harder to keep track of dependencies this way.

**Comment by fisharebest** [comment]
> * Boot the (custom) modules earlier
> * Do not inject dependencies in the Constructor, but only when they are actually used the first time.

There are two ways to obtain an IndividualFactory (or any other object).

1) Dependency injection.  This is the pattern used throughout the code.

2) Obtain from the container.  We generally use this only for external resources, such as filesystems and caches.

For objects that are created **after** we boot the modules, both will work exactly the same.

For objects that are created **before** we boot the modules, both will *appear* to work. But may give different factory objects.  There will be no difference for the core code - just for people using your module.

If we are creating factory objects to support your module, then there is a problem when the easy/default/obvious way to use them is incompatible with your module.

I really do like the factory methods.  It is good to separate the logic of indivduals/families/etc. from the database.  But I do not see a good way to allow modules to override them.

You have two requirements.

1) create new types of record (`_LOC` = SharedLocation).  What if two modules want to create a `_LOC` object?

2) override exising classes (`Individual`).  What if two modules want to modify `Individual` ?

Maybe a solution is to pass all new objects to the modules?

e.g.

```
$record = new GedcomRecord(...);

foreach ($modules as $module) {
    $record = $module->createRecord($record);
}
```

The module could contain this:

```
function createRecord(GedcomRecord $record): GedcomRecord
{
  if ($record type is `_LOC`) {
    return new SharedLocation(...);
  } else {
    return $record;
  }
}
```

**Comment by ric2016** [comment]
These 'what if two modules modify the same part of the system' problems occur elsewhere as well, e.g. when a module changes a view. I don't think it's possible to handle them in general, other than 'first (or last) change wins'.

`foreach ($modules as $module) {
    $record = $module->createRecord($record);
}`

I don't think this would actually allow two modules creating e.g. _LOC objects to work together, unless they are already aware of the other module being potentially enabled. In general, the last module would be just as likely to simply replace the previous module's changes as with the current solution.

> There are two ways to obtain an IndividualFactory (or any other object).

I'm not sure I understand the difference - 'Dependency injection' is the case where a constructor argument is resolved via the container? So ultimately in both cases, the object is obtained from the container? 

Maybe just disallow dependency injection for factories then?

**Comment by ric2016** [comment]
> There are two ways to obtain an IndividualFactory (or any other object).

Perhaps this should be addressed first more generally in the overall architecture - Is it a good idea to use the container for both purposes?

See e.g. [here](https://martinfowler.com/articles/injection.html#ServiceLocatorVsDependencyInjection) - Basically, we don't have either Service Locator or Dependency Injection, but both concepts mixed, and in particular both resolved via the same container.

(By the way, the PSR-11 spec advises against using the container for the service locator pattern, see [here](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-11-container.md#13-recommended-usage))

If we want dependency injection in general, but a service locator for specific cases (external resources, such as filesystems and caches, as you pointed out; and maybe now the factories as well), should we perhaps make the distinction clearer e.g. by using separate containers?

**Pull request closed without merging**
