### PR TITLE
Fixed bug in the statistics distribution diagram, transferring string…

### PR DESCRIPTION
**Pull request by magicsunday**
… values instead of integers

### CODE REVIEW

**Comment by magicsunday** [comment]
Hi @fisharebest, could you please take a look at this small fix?

**Comment by fisharebest** [comment]
Do you think it would be better to modify `function statsPlaces()` to return an `int`?

**Comment by magicsunday** [comment]
I changed the `statsPlaces` method to return integer values.

**Comment by fisharebest** [comment]
Looks good.  Thanks!

**Pull request merged**
