### PR TITLE
Simplified Chinese language file translation repair

### PR DESCRIPTION
**Pull request by xmlf**
In the Simplified Chinese language, fix some translations can't display the problem, re-optimize, complete all translations.

### CODE REVIEW

**Comment by magicsunday** [comment]
@fisharebest Please fix the translation server

**Comment by xmlf** [comment]
In the previous Simplified and Traditional language files, there were many places that were translated but not displayed correctly. And the translation results in many places are difficult to understand.
I fixed it with poedit and I will continue to optimize after the webtrees 2.0 beta release. Includes files for traditional Chinese languages.

**Comment by fisharebest** [comment]
Can you:

1) remove the `.mo` file.  These are not saved in the source code.
2) save the `.po` file with linux line endings `\n`, not msdos line endings `\r\n`.
3) do not change the header in the `.po` file - you have changed it from `zh-Hans` to `zh-CN`

**Comment by xmlf** [comment]
I am using poedit to edit under windows. The msdos line endings and header should be automatically modified by poedit. Although this modified language file works fine on the website.
But, I will find out immediately how to change the poedit default settings to meet your requirements.
Thank you very much for your guidance.

**Comment by xmlf** [comment]
By checking the poedit settings, the default language code in the poedit project properties is zh_CN, which I guess is based on my operating system language. I can't change it to zh_Hans via poedit, so I can only make manual changes by using editplus.
I have completed the modification according to your requirements, please help me check if it is correct, thank you!

**Comment by fisharebest** [comment]
> I have completed the modification according to your requirements, please help me check if it is correct

That's great.  Thanks!

**Comment by xmlf** [comment]
Most thank you guys are you! Thank you for creating such a great project.I am very much looking forward to the URL pseudo-static feature.

**Pull request merged**
