### PR TITLE
Google maps form in bootstrap layout

### PR DESCRIPTION
**Pull request by JustCarmen**
I've split the changes into multiple commits so it is easier for you to see the changes.

### CODE REVIEW

**Comment by JustCarmen** [comment]
Some checks failed. What should I do to correct this?

**Comment by fisharebest** [comment]
> Some checks failed. What should I do to correct this?

You can ignore this one.  It means that after your change, a smaller % of lines of code were covered by the unit-tests.

I guess your new code simply has more lines than the old code.

**Comment by fisharebest** [comment]
PS:

When a `<label>` encloses an `<input>`, then you do not need the `for="XXX"` and `id="XXX'`.

Some validation tools get this wrong ;-)

**Comment by JustCarmen** [comment]
>> When a <label> encloses an <input>, then you do not need the for="XXX" and id="XXX'
Didn't know that. Do you want me to change it back?

**Comment by fisharebest** [comment]
> Do you want me to change it?

If/when you have some spare time...

**Pull request merged**
