### PR TITLE
Fix Geographic Data links

### PR DESCRIPTION
**Pull request by ric2016**
Fix error occurring when opening 'Geographic Data' with custom PlaceHierarchyListModule enabled
(discussed in https://www.webtrees.net/index.php/en/forum/help-for-2-0/34847-error-when-clicking-on-geographic-data)

### CODE REVIEW

**Comment by fisharebest** [comment]
As you have discovered, the `listUrl()` function requires a tree object - which is not immediately available.

Instead of `new Tree()`, I think it is better to use `$tree_service->all()->get($tree_name)`.

Also, the logic for generating the URL probably does not belong in the view.

The `Place` object contains the code for generating the URL.

Perhaps the line `$this->map_data_service->activePlaces($parent)` should be modifed to generate `Place` objects?

**Comment by ric2016** [comment]
I have adjusted the code to use TreeService, as suggested.

Regarding: "Also, the logic for generating the URL probably does not belong in the view."

I agree, but this is a more complex change, which I would consider to be independent of the bugfix (the view currently generates the url as well, via `route`, so this isn't worse than before in that regard).

So this should be changed separately if necessary (following 'one change per PR').

**Comment by fisharebest** [comment]
Can you fix the merge conflicts?

**Comment by ric2016** [comment]
Updated version: #3487.

**Pull request closed without merging**
