### PR TITLE
Remove global variable usage and other chart work

### PR DESCRIPTION
**Pull request by ddrury**
Removed global variables from charts and chart related functions (either pass variable as a parameter or obtain from controller)

Most charts - remove unused or broken parameters from forms, remove unused variables from controllers

Pedigree chart remove chart and canvas css offset and remove most (but not all) embedded 'magic numbers'

### CODE REVIEW

**Comment by fisharebest** [comment]
Thanks for this!

**Comment by makitso** [comment]
Dave,  just a FYI, your latest change has impacted the printing of the pedigree chart.

**Comment by ddrury** [comment]
How are you printing it? Any particular browser?

**Comment by makitso** [comment]
I am using FF on Ubuntu and doing a preview.

You need to remove the top from the @media print

     #pedigree_chart {
         left: -40px;
         top:  -260px;
     }

**Comment by ddrury** [comment]
Good catch - missed that one

**Pull request merged**
