### PR TITLE
Google Maps enhancement

### PR DESCRIPTION
**Pull request by ddrury**
A possible solution for the situation where many markers are located at the same co-ordinates.

Uses a small javascript library [Overlapping Marker Spiderfier](https://github.com/jawj/OverlappingMarkerSpiderfier) to expand markers in a spiral centred on the co-ordinates when the marker is clicked - implemented for the Individual tab and the pedigree map.

With this solution the varied icon shapes & sizes used in an attempt to reveal the hidden points become redundant and are removed (along with some other redundant icons) this allows the removal of large chunks of javascript related to this.

NOTE: During development of this, It was discovered that the "shadow" facility for marker icons had been removed in googlemaps api version 3.14 so even if this PR is rejected, all marker shadow related functionality should be removed.

### CODE REVIEW

**Comment by fisharebest** [comment]
The markers have tool-tips (the name of the individual).
For the "multiple" markers, we see the tool-tip of just one of the names.

Is there a way to give different tool-tips to these multiple markers.  Maybe "5 individuals"?
If not, then would it be less confusing not to have them at all?

PS - there is a `.php_cs` config file for php-cs-fixer.  `php-cs-fixer fix` would tell you that there needs to be a blank line before `return` statements.

**Comment by ddrury** [comment]
> For the "multiple" markers, we see the tool-tip of just one of the names.

I was already investigating the possibility of having a different icon for the groups (where the tooltip would clearly need removing) - apparently it can be done but will need a bit of work on my part.

> PS - there is a .php_cs config file for php-cs-fixer. php-cs-fixer fix would tell you that there needs to be a blank line before return statements.

I just tried this and it trampled all over the code - clearly I did something wrong :-(

**Comment by fisharebest** [comment]
> I just tried this and it trampled all over the code - clearly I did something wrong :-(

Odd.  When I ran it, it just added two missing blank lines.

**Comment by ddrury** [comment]
Will be resubmitted from different branch

**Pull request closed without merging**
